# Challenge 1: Geodemographic Classification

In this challenge, you will replicate the process of creating a geodemographic classification using the k-means clustering algorithm. Please select any city in the UK except London, Liverpool, or Glasgow. The main goal is to generate a meaningful and informative classification that captures the diversity of areas in your dataset using the census data ( For England, you can try to use the 2021 or 2011 census, and for Scotland, you need to use the 2011 census data) 

1. Define the main goal for the geodemographic classification (marketing, retail and service planning). 
2. Look for census data from the selected city for which you would like to generate the geodemographic classification.
3. The census data at the Output Area OA level. Select multiple topics of at least four topics (socio-demographics, economics, health, and so on). Describe your topic selection accordingly based on the goal of your geodemographic classification. For example, if your geodemographics are related to marketing, Economic variables might be the appropriate selection. 
4. Identify the variables that will be crucial for effectively segmenting neighbourhoods. Evaluate how this choice may impact the classification results, including a DEA analysis.
5. Prepare, adjust or clean the dataset addressing any missing values or outliers that could distort the clustering results.
6. Include standardisation between areas and variables. Make an appropriate analysis and adjust the variable selection accordingly for any multicollinearity.
7. Utilize the k-means clustering algorithm to create a classification based on the selected variables.
8. Define the optimum number of clusters (i.e., using the Elblow method). Experiment with different values of k.
9. Evaluate your cluster groups (e.g., using PCA) and interpret your cluster centres. Describe your results and repeat the process to adjust the variable selection and cluster groups to provide more meaningful results for your geodemographic goal. Interpret the characteristics of each cluster. What demographic patterns or similarities are prevalent within each group?
10. Map the final cluster groups
11. Finish the analysis by naming the final clusters and plotting a final map that includes the census values and the provided names.
12. Finally, acknowledge the subjective nature of classification and make analytical decisions to produce an optimum classification for your specific purpose. Reflect on the challenges and insights gained during the classification process. Ensure you document your analytical decisions and the rationale behind any important decision. Once your geodemographics are constructed, describe the potential use cases for the geodemographic classification you have built based on your initial goal.

In [ ]:
#defining the main goal for the geodemographic classification

I will be examining data for the city of Brigthton and Hove from a marketing perspective using data from the 2021 Census for England and Wales.

**Study area**: Brighton and Hove
**Geography (spatial units)** Output Areas 
**Dataset**: 2021 United Kingdom Census 

**Census Variables Used** - 
- Age structure
- Economic activity
- Ethnicity
- General Health
- Highest Level of Educational Qualification
- Industry
- Living Arrangement
- Marital and civil partnership status
- Religion
- Sex

Reference: ONS (2021). Census - Office for National Statistics. [online] Ons.gov.uk. Available at: https://www.ons.gov.uk/census.

In [ ]:
#identifying variables to help with a marketing analysis

In [ ]:
#preparing the variables for analysis

In [38]:
#exploring one variable for analysis - ethnicity to look at how the columns are
import pandas as pd
import geopandas as gpd
age_directory = "data/lab_raw_data/agebrighton.csv"
age = gpd.read_file(age_directory)
age.head()

,Output Areas,Age (6 categories) Code,Age (6 categories),Observation Age
0,E00085001,1,Aged 15 years and under,13
1,E00085001,2,Aged 16 to 24 years,37
2,E00085001,3,Aged 25 to 34 years,58
3,E00085001,4,Aged 35 to 49 years,71
4,E00085001,5,Aged 50 to 64 years,40

In [39]:
#reading in selected raw census data (csv files)
import pandas as pd
import os

csv_directory = "data/lab_raw_data"

csv_files = [file for file in os.listdir(csv_directory) if file.endswith(".csv")]

# an empty DataFrame to store the merged data
merged_data = pd.DataFrame()

In [40]:
#merging the csv files
for csv_file in csv_files:
    csv_path = os.path.join(csv_directory, csv_file)
    df_csv = pd.read_csv(csv_path, low_memory=False)
    merged_data = pd.concat([merged_data, df_csv], axis=1)

merged_data.to_csv("data/lab_raw_data/merged_lab_data.csv", index=False)

In [41]:
#checking out first few columns of merged variables
merged_data.head()

,Output Areas,Age (6 categories) Code,Age (6 categories),Observation Age,Economic activity status (7 categories) Code,Economic activity status (7 categories),Observation Economic activity status,Ethnic group (20 categories) Code,Ethnic group (20 categories),Observation Ethnic group,...,Observation Religion,Sex (2 categories) Code,Sex (2 categories),Observation Sex,Religion (10 categories) Code,Religion (10 categories),Observation Religion,Sex (2 categories) Code,Sex (2 categories),Observation Sex
0,E00085001,1.0,Aged 15 years and under,13.0,-8.0,Does not apply,13.0,-8,Does not apply,0,...,0.0,1.0,Female,118.0,-8.0,Does not apply,0.0,1.0,Female,118.0
1,E00085001,2.0,Aged 16 to 24 years,37.0,1.0,Economically active (excluding full-time stude...,133.0,1,"Asian, Asian British or Asian Welsh: Bangladeshi",0,...,127.0,2.0,Male,121.0,1.0,No religion,127.0,2.0,Male,121.0
2,E00085001,3.0,Aged 25 to 34 years,58.0,2.0,Economically active (excluding full-time stude...,7.0,2,"Asian, Asian British or Asian Welsh: Chinese",2,...,59.0,1.0,Female,181.0,2.0,Christian,59.0,1.0,Female,181.0
3,E00085001,4.0,Aged 35 to 49 years,71.0,3.0,Economically active and a full-time student: I...,10.0,3,"Asian, Asian British or Asian Welsh: Indian",5,...,1.0,2.0,Male,145.0,3.0,Buddhist,1.0,2.0,Male,145.0
4,E00085001,5.0,Aged 50 to 64 years,40.0,4.0,Economically active and a full-time student: U...,7.0,4,"Asian, Asian British or Asian Welsh: Pakistani",2,...,3.0,1.0,Female,123.0,4.0,Hindu,3.0,1.0,Female,123.0

In [42]:
#renaming categories so that data manipulation is easier
short_column_names = {
    'Output Areas': 'OA',
    'Age (6 categories)': 'Age',
    'Observation Age': 'Age_Obs',
    'Economic activity status (7 categories)': 'Economic_status',
    'Observation Economic activity status': 'Economic_Obs',
    'Ethnic group (20 categories)': 'Ethnic_group',
    'Observation Ethnic group': 'Ethnic_Obs',
    'General health (4 categories)': 'Health',
    'Observation General health': 'Health_Obs',
    'Highest level of qualification (7 categories)': 'Highest_qual',
    'Observation Highest level of qualification': 'Highest_Obs',
    'Industry (current) (9 categories)': 'Industry',
    'Observation Industry (current)': 'Industry_Obs',
    'Living arrangements (11 categories)': 'Living_arr',
    'Observation Living arrangements': 'Living_Obs',
    'Marital and civil partnership status (6 categories)': 'Marital_stat',
    'Observation Marital and civil partnership status': 'Marital_Obs',
    'Religion (10 categories)': 'Religion',
    'Observation Religion': 'Religion_Obs',
    'Sex (2 categories)': 'Sex',
    'Observation Sex': 'Sex_Obs'
}

brighton_census_data = merged_data.rename(columns=short_column_names)

In [43]:
#reviewing new names of columns
brighton_census_data.head()

,OA,Age (6 categories) Code,Age,Age_Obs,Economic activity status (7 categories) Code,Economic_status,Economic_Obs,Ethnic group (20 categories) Code,Ethnic_group,Ethnic_Obs,...,Religion_Obs,Sex (2 categories) Code,Sex,Sex_Obs,Religion (10 categories) Code,Religion,Religion_Obs,Sex (2 categories) Code,Sex,Sex_Obs
0,E00085001,1.0,Aged 15 years and under,13.0,-8.0,Does not apply,13.0,-8,Does not apply,0,...,0.0,1.0,Female,118.0,-8.0,Does not apply,0.0,1.0,Female,118.0
1,E00085001,2.0,Aged 16 to 24 years,37.0,1.0,Economically active (excluding full-time stude...,133.0,1,"Asian, Asian British or Asian Welsh: Bangladeshi",0,...,127.0,2.0,Male,121.0,1.0,No religion,127.0,2.0,Male,121.0
2,E00085001,3.0,Aged 25 to 34 years,58.0,2.0,Economically active (excluding full-time stude...,7.0,2,"Asian, Asian British or Asian Welsh: Chinese",2,...,59.0,1.0,Female,181.0,2.0,Christian,59.0,1.0,Female,181.0
3,E00085001,4.0,Aged 35 to 49 years,71.0,3.0,Economically active and a full-time student: I...,10.0,3,"Asian, Asian British or Asian Welsh: Indian",5,...,1.0,2.0,Male,145.0,3.0,Buddhist,1.0,2.0,Male,145.0
4,E00085001,5.0,Aged 50 to 64 years,40.0,4.0,Economically active and a full-time student: U...,7.0,4,"Asian, Asian British or Asian Welsh: Pakistani",2,...,3.0,1.0,Female,123.0,4.0,Hindu,3.0,1.0,Female,123.0

In [44]:
#cleaning up the merged variables dataset for better visibility during data analysis - clearing out irrelevant columns
keep_cols= [
    'OA',
    'Age',
    'Age_Obs',
    'Economic_status',
    'Economic_Obs',
    'Ethnic_group',
    'Ethnic_Obs',
    'Health',
    'Health_Obs',
    'Highest_qual',
    'Highest_Obs',
    'Industry',
    'Industry_Obs',
    'Living_arr',
    'Living_Obs',
    'Marital_stat',
    'Marital_Obs',
    'Religion',
    'Religion_Obs',
    'Sex',
    'Sex_Obs'
]
    
brighton_census_data = brighton_census_data[keep_cols]

In [45]:
#checking the new table
brighton_census_data.head()

,OA,OA,OA,Age,Age,Age,Age_Obs,Age_Obs,Age_Obs,Economic_status,...,Religion,Religion_Obs,Religion_Obs,Religion_Obs,Sex,Sex,Sex,Sex_Obs,Sex_Obs,Sex_Obs
0,E00085001,E00085001,E00085001,Aged 15 years and under,Aged 15 years and under,Aged 15 years and under,13.0,13.0,13.0,Does not apply,...,Does not apply,0.0,0.0,0.0,Female,Female,Female,118.0,118.0,118.0
1,E00085001,E00085001,E00085001,Aged 16 to 24 years,Aged 16 to 24 years,Aged 16 to 24 years,37.0,37.0,37.0,Economically active (excluding full-time stude...,...,No religion,127.0,127.0,127.0,Male,Male,Male,121.0,121.0,121.0
2,E00085001,E00085001,E00085001,Aged 25 to 34 years,Aged 25 to 34 years,Aged 25 to 34 years,58.0,58.0,58.0,Economically active (excluding full-time stude...,...,Christian,59.0,59.0,59.0,Female,Female,Female,181.0,181.0,181.0
3,E00085001,E00085001,E00085001,Aged 35 to 49 years,Aged 35 to 49 years,Aged 35 to 49 years,71.0,71.0,71.0,Economically active and a full-time student: I...,...,Buddhist,1.0,1.0,1.0,Male,Male,Male,145.0,145.0,145.0
4,E00085001,E00085001,E00085001,Aged 50 to 64 years,Aged 50 to 64 years,Aged 50 to 64 years,40.0,40.0,40.0,Economically active and a full-time student: U...,...,Hindu,3.0,3.0,3.0,Female,Female,Female,123.0,123.0,123.0

In [46]:
#eliminating any duplicates in the data
brighton_census_data = brighton_census_data.loc[:, ~brighton_census_data.columns.duplicated()]
brighton_census_data.columns.tolist()

['OA',
 'Age',
 'Age_Obs',
 'Economic_status',
 'Economic_Obs',
 'Ethnic_group',
 'Ethnic_Obs',
 'Health',
 'Health_Obs',
 'Highest_qual',
 'Highest_Obs',
 'Industry',
 'Industry_Obs',
 'Living_arr',
 'Living_Obs',
 'Marital_stat',
 'Marital_Obs',
 'Religion',
 'Religion_Obs',
 'Sex',
 'Sex_Obs']

In [47]:
#checking that duplicates are eliminated
brighton_census_data.head()

,OA,Age,Age_Obs,Economic_status,Economic_Obs,Ethnic_group,Ethnic_Obs,Health,Health_Obs,Highest_qual,...,Industry,Industry_Obs,Living_arr,Living_Obs,Marital_stat,Marital_Obs,Religion,Religion_Obs,Sex,Sex_Obs
0,E00085001,Aged 15 years and under,13.0,Does not apply,13.0,Does not apply,0,Does not apply,0.0,Does not apply,...,Does not apply,96.0,Does not apply,13.0,Does not apply,13.0,Does not apply,0.0,Female,118.0
1,E00085001,Aged 16 to 24 years,37.0,Economically active (excluding full-time stude...,133.0,"Asian, Asian British or Asian Welsh: Bangladeshi",0,Very good or good health,192.0,No qualifications,...,"A, B, D, E Agriculture, energy and water",1.0,Living in an opposite-sex couple: Married or i...,40.0,Never married and never registered a civil par...,145.0,No religion,127.0,Male,121.0
2,E00085001,Aged 25 to 34 years,58.0,Economically active (excluding full-time stude...,7.0,"Asian, Asian British or Asian Welsh: Chinese",2,Fair health,34.0,Level 1 and entry level qualifications: 1 to 4...,...,C Manufacturing,8.0,Living in a same-sex couple: Married or in a c...,4.0,Married or in a registered civil partnership,44.0,Christian,59.0,Female,181.0
3,E00085001,Aged 35 to 49 years,71.0,Economically active and a full-time student: I...,10.0,"Asian, Asian British or Asian Welsh: Indian",5,Bad or very bad health,13.0,Level 2 qualifications: 5 or more GCSEs (A* to...,...,F Construction,5.0,"Living in a couple: Separated, but still marri...",0.0,"Separated, but still legally married or still ...",8.0,Buddhist,1.0,Male,145.0
4,E00085001,Aged 50 to 64 years,40.0,Economically active and a full-time student: U...,7.0,"Asian, Asian British or Asian Welsh: Pakistani",2,Does not apply,0.0,Level 3 qualifications: 2 or more A levels or ...,...,"G, I Distribution, hotels and restaurants",24.0,Living in an opposite-sex couple: Cohabiting,36.0,Divorced or civil partnership dissolved,26.0,Hindu,3.0,Female,123.0

In [48]:
brighton_census_data.columns

Index(['OA', 'Age', 'Age_Obs', 'Economic_status', 'Economic_Obs',
       'Ethnic_group', 'Ethnic_Obs', 'Health', 'Health_Obs', 'Highest_qual',
       'Highest_Obs', 'Industry', 'Industry_Obs', 'Living_arr', 'Living_Obs',
       'Marital_stat', 'Marital_Obs', 'Religion', 'Religion_Obs', 'Sex',
       'Sex_Obs'],
      dtype='object')

In [49]:
#saving this new dataframe, with census data organised into one complete table, as a new csv
brighton_census_data.to_csv("data/lab_raw_data/brighton_census_data.csv", index=False)

In [50]:
#merging the census data with the output area shapefile for Brighton and Hove
import pandas as pd
import geopandas as gpd

shp_path = "data/lab_raw_data/OA_2021_EW_BGC_V2.shp"
gdf = gpd.read_file(shp_path)

csv_path = "data/lab_raw_data/brighton_census_data.csv"
csv_data = pd.read_csv(csv_path, low_memory=False)

# merging the GeoDataFrame with the DataFrame based on the oa_code
merged_data = gdf.merge(csv_data, left_on='OA21CD', right_on='OA', how='left')
#saving it as a shapefile
merged_data.to_file('data/lab_raw_data/brighton_census_data.shp', index=False)

C:\Users\user\AppData\Local\Temp\ipykernel_5036\2582564262.py:14: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  merged_data.to_file('data/lab_raw_data/brighton_census_data.shp', index=False)
C:\Users\user\MiniForge\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Economic_status' to 'Economic_s'
  ogr_write(
C:\Users\user\MiniForge\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Economic_Obs' to 'Economic_O'
  ogr_write(
C:\Users\user\MiniForge\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Ethnic_group' to 'Ethnic_gro'
  ogr_write(
C:\Users\user\MiniForge\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Highest_qual' to 'Highest_qu'
  ogr_write(
C:\Users\user\MiniForge\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Highest_Obs' to 'Highest_Ob'
  ogr_write(
C:\Users\user\MiniForge\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Industry_Obs' to 'Industry_O'
  ogr_write(
C:\Users\user\MiniForge\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Marital_stat' to 'Marital_st'
  ogr_write(
C:\Users\user\MiniForge\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Marital_Obs' to 'Marital_Ob'
  ogr_write(
C:\Users\user\MiniForge\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Religion_Obs' to 'Religion_O'
  ogr_write(
C:\Users\user\MiniForge\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Value 'Level 2 qualifications: 5 or more GCSEs (A* to C or 9 to 4), O levels (passes), CSEs (grade 1), School Certification, 1 A level, 2 to 3 AS levels, VCEs, Intermediate or Higher Diploma, Welsh Baccalaureate Intermediate Diploma, NVQ level 2, Intermediate GNVQ, City and Guilds Craft, BTEC First or General Diploma, RSA Diploma' of field Highest_qu has been truncated to 254 characters.  This warning will not be emitted any more for that layer.
  ogr_write(

In [51]:
gdf.head()

,OA21CD,LSOA21CD,LSOA21NM,LSOA21NMW,BNG_E,BNG_N,LAT,LONG,GlobalID,geometry
0,E00000001,E01000001,City of London 001A,None,532250,181864,51.5202,-0.09523,3a44dd3d-5082-4a09-9b9c-3a5fadc811ed,"POLYGON ((532303.492 181814.11, 532213.378 181..."
1,E00000003,E01000001,City of London 001A,None,532171,181819,51.5198,-0.09638,f1216dc8-14d1-4857-9230-cab0641758fb,"POLYGON ((532213.378 181846.192, 532190.539 18..."
2,E00000005,E01000001,City of London 001A,None,532166,181722,51.5190,-0.09649,44d6f70f-549c-4288-9b6d-de2adbf02582,"POLYGON ((532180.131 181763.02, 532219.161 181..."
3,E00000007,E01000001,City of London 001A,None,532088,181473,51.5167,-0.09771,4dd683e1-9a5c-46cf-9e19-8465c8fbb6cb,"POLYGON ((532201.292 181668.18, 532267.728 181..."
4,E00000010,E01000003,City of London 001C,None,532092,182114,51.5225,-0.09741,7476781f-8fe4-4c9b-bde1-0eecbd146dff,"POLYGON ((532127.958 182133.192, 532089.264 18..."

In [52]:
csv_data.head()

,OA,Age,Age_Obs,Economic_status,Economic_Obs,Ethnic_group,Ethnic_Obs,Health,Health_Obs,Highest_qual,...,Industry,Industry_Obs,Living_arr,Living_Obs,Marital_stat,Marital_Obs,Religion,Religion_Obs,Sex,Sex_Obs
0,E00085001,Aged 15 years and under,13.0,Does not apply,13.0,Does not apply,0,Does not apply,0.0,Does not apply,...,Does not apply,96.0,Does not apply,13.0,Does not apply,13.0,Does not apply,0.0,Female,118.0
1,E00085001,Aged 16 to 24 years,37.0,Economically active (excluding full-time stude...,133.0,"Asian, Asian British or Asian Welsh: Bangladeshi",0,Very good or good health,192.0,No qualifications,...,"A, B, D, E Agriculture, energy and water",1.0,Living in an opposite-sex couple: Married or i...,40.0,Never married and never registered a civil par...,145.0,No religion,127.0,Male,121.0
2,E00085001,Aged 25 to 34 years,58.0,Economically active (excluding full-time stude...,7.0,"Asian, Asian British or Asian Welsh: Chinese",2,Fair health,34.0,Level 1 and entry level qualifications: 1 to 4...,...,C Manufacturing,8.0,Living in a same-sex couple: Married or in a c...,4.0,Married or in a registered civil partnership,44.0,Christian,59.0,Female,181.0
3,E00085001,Aged 35 to 49 years,71.0,Economically active and a full-time student: I...,10.0,"Asian, Asian British or Asian Welsh: Indian",5,Bad or very bad health,13.0,Level 2 qualifications: 5 or more GCSEs (A* to...,...,F Construction,5.0,"Living in a couple: Separated, but still marri...",0.0,"Separated, but still legally married or still ...",8.0,Buddhist,1.0,Male,145.0
4,E00085001,Aged 50 to 64 years,40.0,Economically active and a full-time student: U...,7.0,"Asian, Asian British or Asian Welsh: Pakistani",2,Does not apply,0.0,Level 3 qualifications: 2 or more A levels or ...,...,"G, I Distribution, hotels and restaurants",24.0,Living in an opposite-sex couple: Cohabiting,36.0,Divorced or civil partnership dissolved,26.0,Hindu,3.0,Female,123.0

In [53]:
list(merged_data.columns)

['OA21CD',
 'LSOA21CD',
 'LSOA21NM',
 'LSOA21NMW',
 'BNG_E',
 'BNG_N',
 'LAT',
 'LONG',
 'GlobalID',
 'geometry',
 'OA',
 'Age',
 'Age_Obs',
 'Economic_status',
 'Economic_Obs',
 'Ethnic_group',
 'Ethnic_Obs',
 'Health',
 'Health_Obs',
 'Highest_qual',
 'Highest_Obs',
 'Industry',
 'Industry_Obs',
 'Living_arr',
 'Living_Obs',
 'Marital_stat',
 'Marital_Obs',
 'Religion',
 'Religion_Obs',
 'Sex',
 'Sex_Obs']

In [54]:
merged_data.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 193560 entries, 0 to 193559
Data columns (total 31 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   OA21CD           193560 non-null  object
 1   LSOA21CD         193560 non-null  object
 2   LSOA21NM         193560 non-null  object
 3   LSOA21NMW        10275 non-null   object
 4   BNG_E            193560 non-null  int64
 5   BNG_N            193560 non-null  int64
 6   LAT              193560 non-null  float64
 7   LONG             193560 non-null  float64
 8   GlobalID         193560 non-null  object
 9   geometry         193560 non-null  geometry
 10  OA               5616 non-null    object
 11  Age              5616 non-null    object
 12  Age_Obs          5616 non-null    float64
 13  Economic_status  5616 non-null    object
 14  Economic_Obs     5616 non-null    float64
 15  Ethnic_group     5616 non-null    object
 16  Ethnic_Obs       5616 non-null    float64
 17  Health           3744 non-null    object
 18  Health_Obs       3744 non-null    float64
 19  Highest_qual     5616 non-null    object
 20  Highest_Obs      5616 non-null    float64
 21  Industry         5616 non-null    object
 22  Industry_Obs     5616 non-null    float64
 23  Living_arr       5616 non-null    object
 24  Living_Obs       5616 non-null    float64
 25  Marital_stat     5616 non-null    object
 26  Marital_Obs      5616 non-null    float64
 27  Religion         5616 non-null    object
 28  Religion_Obs     5616 non-null    float64
 29  Sex              1872 non-null    object
 30  Sex_Obs          1872 non-null    float64
dtypes: float64(12), geometry(1), int64(2), object(16)
memory usage: 45.8+ MB

In [55]:
merged_data.shape

(193560, 31)

In [56]:
merged_data.head()

,OA21CD,LSOA21CD,LSOA21NM,LSOA21NMW,BNG_E,BNG_N,LAT,LONG,GlobalID,geometry,...,Industry,Industry_Obs,Living_arr,Living_Obs,Marital_stat,Marital_Obs,Religion,Religion_Obs,Sex,Sex_Obs
0,E00000001,E01000001,City of London 001A,None,532250,181864,51.5202,-0.09523,3a44dd3d-5082-4a09-9b9c-3a5fadc811ed,"POLYGON ((532303.492 181814.11, 532213.378 181...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E00000003,E01000001,City of London 001A,None,532171,181819,51.5198,-0.09638,f1216dc8-14d1-4857-9230-cab0641758fb,"POLYGON ((532213.378 181846.192, 532190.539 18...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E00000005,E01000001,City of London 001A,None,532166,181722,51.5190,-0.09649,44d6f70f-549c-4288-9b6d-de2adbf02582,"POLYGON ((532180.131 181763.02, 532219.161 181...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E00000007,E01000001,City of London 001A,None,532088,181473,51.5167,-0.09771,4dd683e1-9a5c-46cf-9e19-8465c8fbb6cb,"POLYGON ((532201.292 181668.18, 532267.728 181...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E00000010,E01000003,City of London 001C,None,532092,182114,51.5225,-0.09741,7476781f-8fe4-4c9b-bde1-0eecbd146dff,"POLYGON ((532127.958 182133.192, 532089.264 18...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
#Descriptive Analysis - DEA
merged_data['Economically active: Employee: Part-time'].describe()

KeyError: 'Economically active: Employee: Part-time'

In [ ]:
#corrections - old code

In [ ]:
#working with only the lower tier local authority of Brighton and Hove, and the output areas inside of them
import pandas as pd
import geopandas as gpd

#first have to import the shapefile of local authority boundaries for England
gdf_path = "data/lab_raw_data/LPA_APR_2022_UK_BFC.shp"
gdf = gpd.read_file(gdf_path)

gdf.head()

In [ ]:
#filtering the local authority boundaries to only include Brighton and Hove
brighton_gdf = gdf[gdf["LPA22CD"] == "E60000222"]
print(brighton_gdf)

In [ ]:
#saving the local authority boundary of Brighton and Hove
brighton_gdf.to_file("brighton_hove_boundaries.shp", driver="ESRI Shapefile")

In [ ]:
#visualising the boundary of our selected city of Study: Brighton and Hove
import matplotlib.pyplot as plt
brighton_gdf.plot(figsize=(8,6), edgecolor="black", color="lightblue")
plt.title("Brighton and Hove Boundary")
plt.show()

In [ ]:
#merging the GeoDataFrame of our spatial area with the DataFrame of variables

#loading our dataframe for variables for Brighton and Hove
csv_path = "data/lab_raw_data/brighton_census_data.csv"
csv_data = pd.read_csv(csv_path, low_memory=False)

In [ ]:
#clipping the OA for England to the spatial extent of Brighton
#inputting the OA
OA_path = "data/lab_raw_data/OA_2021_EW_BGC_V2.shp"
OA = gpd.read_file(OA_path, low_memory=False)
#clipping to my brighton and hove geodataframe extent
OA_brighton = OA.clip(brighton_gdf.geometry)
OA_brighton.to_file("data/lab_raw_data/OA_brighton.shp")
OA_brighton.head()

In [ ]:
#visualising the boundaries of Brighton and Hove
OA_brighton.plot

In [ ]:
#merging the boundaries of brighton and the df of census data
merged_brighton_data = OA_brighton.merge(csv_data, left_on='OA21CD', right_on='Output Areas', how='left')

#displaying the first few rows to verify a successful merge
merged_brighton_data.head()

#saving the merged data as a new shapefile
merged_brighton_data.to_file("data/lab_raw_data/merged_brighton_data.shp", driver="ESRI Shapefile")

In [ ]:
#Descriptive Statistics Analysis - DEA of variables

In [ ]:
#summary statistics
merged_brighton_data['Economically active: Employee: Part-time'].describe() #example -> can change

In [ ]:
merged_brighton_data.Married.describe() #example to change

In [ ]:
#looking at four different variables

import seaborn as sns
import matplotlib.pyplot as plt

attributes_to_plot = ['____',
                      '__',
                      '___',
                      '____']

plt.figure(figsize=(12, 8))

for i, attribute in enumerate(attributes_to_plot, 1):
    plt.subplot(2, 2, i)
    sns.violinplot(x=merged_data[attribute])
    plt.title(attribute)
    plt.xlabel('')
    plt.ylabel('')

plt.tight_layout()
plt.show()